### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by GelosSnake** [darx0r/Stingray#1]
First thanks for the plugin, seems pretty awesome. Just had a quick go at it and got this error when exiting IDA. 

FYI

![screen shot 2015-10-09 at 14 29 09](https://cloud.githubusercontent.com/assets/5004714/10392698/36d01ed4-6e92-11e5-9b50-dc04d86e0afe.png)

**Comment by darx0r** [comment]
For some reason it seems like your %IDAPATH\cfg directory is read only. 
I simulated your scenario by setting my cfg dir to read only and the same error came out.

I would suggest you to make it non read only :)

**Comment by GelosSnake** [comment]
hmmm weird wonder what happend. 
Thanks! solved
