### ISSUE TITLE
Can't see the plugin in menu

### ISSUE THREAD

**Issue by Mila432** [darx0r/Stingray#4]
Is there a min version for it ?
Because its not showing under Edit -> Plugins

It says IDA (Hex Rays Interactive Disassembler) version >= 6 with IDAPython and I have 6.8

**Comment by darx0r** [comment]
Can you verify that the plugin is loaded? The hotkey is working? Other menus (config) are there?

**Comment by Mila432** [comment]
Updated to new IDA python , working now!
