### ISSUE TITLE
add_menu_item no longer supported in IDA 7.0

### ISSUE THREAD

**Issue by GelosSnake** [darx0r/Stingray#5]
Hi guys,

Seems like add_menu_item is no longer supported in IDA 7.0 and therefor the plugin breaks.

<img width="773" alt="screenshot 2017-12-11 01 38 17" src="https://user-images.githubusercontent.com/5004714/33810908-0b96ea24-de14-11e7-9a1f-2889d7f0d787.png">

**Comment by darx0r** [comment]
see #6
