### ISSUE TITLE
Plugin does not work with IDA 7.1

### ISSUE THREAD

**Issue by kaipyroami** [darx0r/Stingray#7]
Plugin does not work with IDA 7.1.
The Plugin is not recognized.

**Comment by darx0r** [comment]
"The Plugin is not recognized" - any exceptions? output in the output window? Did you placed it in the right place?

**Comment by Mila432** [comment]
@darx0r its "working" just the output window is empty

**Comment by TheLordOfTheKings** [comment]
IDA Pro 7.2 says:
No handlers could be found for logger "Stingray"
And plugin doesn't work.

**Comment by AidanMcCarthy** [comment]
Also seeing the same issue

> No handlers could be found for logger "Stingray"
